/// Flutter icons YSY
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YSY
///      fonts:
///       - asset: fonts/YSY.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class YSY {
  YSY._();

  static const _kFontFam = 'YSY';

  static const IconData tag = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData phone_handset = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData pushpin = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData map_marker = const IconData(0xe833, fontFamily: _kFontFam);
}
